name: Register
description: Register a Subdomain
title: "Register"
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: "<domain>"
  - type: input
    id: domain
    attributes:
      label: Subdomain Name
      description: What subdomain do you want to register?
      placeholder: ex. something.is-probably.gay
      value: ".is-probably.gay"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "<domain-end><dns>"
  - type: input
    id: dns
    attributes:
      label: DNS Record
      description: Where should the domain point to? You can type in either an IP address or a domain, and it will automatically detect whether to use A, AAAA, or CNAME.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "<dns-end><agreement>"
  - type: checkboxes
    id: checked
    attributes:
      label: Agreement
      options:
        - label: I have ensured that no one registered this subdomain
          required: true
        - label: I have ensured that I did not reach the five subdomain limit
          required: true
  - type: markdown
    attributes:
      value: "<agreement-end>"
