name: Register
description: Register a subdomain
title: "Registration"
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: "<!\u2D\u2Ddomain\u2D\u2D>"
  - type: input
    id: domain
    attributes:
      label: Subdomain Name
      description: What subdomain do you want to register?
      placeholder: ex. something.is-probably.gay
      value: ".is-probably.gay"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "<!\u2D\u2Ddomain-end\u2D\u2D><!\u2D\u2Ddns\u2D\u2D>"
  - type: input
    id: dns
    attributes:
      label: DNS Record
      description: Where should the domain point to? You can type in either an IP address or a domain, and it will automatically detect whether to use A, AAAA, or CNAME.
    validations:
      required: true
   - type: markdown
    attributes:
      value: "<!\u2D\u2Ddns-end\u2D\u2D><!\u2D\u2Dagreement\u2D\u2D>"
  - type: checkboxes
    id: checked
    attributes:
      label: Agreement
      options:
        - label: I have ensured that no one registered this subdomain
          required: true
        - label: I have ensured that I did not reach the five subdomain limit
          required: true
  - type: markdown
    attributes:
      value: "<!\u2D\u2Dagreement-end\u2D\u2D>"
