name: "Edit Subdomain"

on:
  issues:
    types: [opened]

jobs:
  Register:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Edit'
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      
      - name: Install Dependencies
        run: npm i cloudflare@3.2.0

      - name: Edit Subdomain
        env:
          EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
          EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          node --no-deprecation scripts/edit > data.csv
          echo "Contents of data.csv:"
          cat data.csv

          comment=$(cut -d "|" -f 2 data.csv)
          reason=$(cut -d "|" -f 1 data.csv)
          domain=$(cut -d "|" -f 3 data.csv)
          
          echo "Comment: $comment"
          echo "Reason: $reason"
          echo "Domain: $domain"

          # Ensure 'domain edit' label exists
          gh label list | grep -q 'domain edit' || gh label create 'domain edit' --color f39c12

          # Update the issue with the new title and label
          gh issue edit ${{ github.event.issue.number }} -t "🌈 Edit $domain" --add-label "domain edit"
          
          # Add success or failure label based on the registration result
          if [ "$reason" = "completed" ]; then
            gh issue edit ${{ github.event.issue.number }} --add-label "success"
          else
            gh issue edit ${{ github.event.issue.number }} --add-label "failed"
          fi
